### ISSUE TITLE
add information about deployed contracts

### ISSUE THREAD

**Issue by marc0olo** [aeternity/dex-contracts-v2#76]
see https://github.com/aeternity/dex-ui/issues/361#issuecomment-1167612348

used compiler version: v6.1.0

**Comment by marc0olo** [comment]
@bogdan-manole is this commit the one that was used for compilation of all contracts? https://github.com/aeternity/dex-contracts-v2/commit/53d86c758e8470f051a64710413a01afc03a8708

**Comment by marc0olo** [comment]
@bogdan-manole as I only see addresses written down for the Router and the WAE contracts, what about the Factory contract? I guess this is also relevant information we should display.

I need the info for all relevant contracts with "fixed" addresses which aren't deployed on-demand like e.g. the Pair contract

**Comment by bogdan-manole** [comment]
> see [aeternity/dex-ui#361 (comment)](https://github.com/aeternity/dex-ui/issues/361#issuecomment-1167612348)
> 
> used compiler version: v6.1.0

The reason for this was for the wallet to show extra details regarding dex operations. The factory is remotely called through the router. Anyway, do you need also the past deployments on testnet, or just the latest ones?

**Comment by bogdan-manole** [comment]
> @bogdan-manole is this commit the one that was used for compilation of all contracts? [53d86c7](https://github.com/aeternity/dex-contracts-v2/commit/53d86c758e8470f051a64710413a01afc03a8708)

latest deployments (testnet and mainnet) are based on that commit

**Comment by marc0olo** [comment]
> > see [aeternity/dex-ui#361 (comment)](https://github.com/aeternity/dex-ui/issues/361#issuecomment-1167612348)
> > used compiler version: v6.1.0
> 
> The reason for this was for the wallet to show extra details regarding dex operations. The factory is remotely called through the router. Anyway, do you need also the past deployments on testnet or just the latest ones?
> 
> For mainnet:
> 
> ```
> factoryAddress: 'ct_2mfj3FoZxnhkSw5RZMcP8BfPoB1QR4QiYGNCdkAvLZ1zfF6paW'
> routerAddress: 'ct_azbNZ1XrPjXfqBqbAh1ffLNTQ1sbnuUDFvJrXjYz7JQA1saQ3'
> waeAddress: 'ct_J3zBY8xxjsRr3QojETNw48Eb38fjvEuJKkQ6KzECvubvEcvCa'
> ```
> 
> For testnet:
> 
> ```
> factoryAddress: 'ct_NhbxN8wg8NLkGuzwRNDQhMDKSKBwDAQgxQawK7tkigi2aC7i9'
> routerAddress: 'ct_MLXQEP12MBn99HL6WDaiTqDbG4bJQ3Q9Bzr57oLfvEkghvpFb'
> waeAddress: 'ct_JDp175ruWd7mQggeHewSLS1PFXt9AzThCDaFedxon8mF8xTRF'
> ```

I only need the latest ones and those you mentioned are the relevant ones, correct? I want to provide a table in the readme where we show that info transparently for everybody to check and wanting to interact with those contract and building applications around it

**Comment by marc0olo** [comment]
@bogdan-manole I see we already had an issue for that 😅
