### ISSUE TITLE
add security audit and provide info in README

### ISSUE THREAD

**Issue by marc0olo** [aeternity/dex-contracts-v2#77]

**Comment by marc0olo** [comment]
@kenodressel @benhus as discussed

**Comment by kenodressel** [comment]
@hanssv do you mind providing a PR with your audit? :)

**Comment by marc0olo** [comment]
> @hanssv do you mind providing a PR with your audit? :)

I think that was more a legal matter of how to incorporate this into the repo. I took an attempt back then for the multisig contract 😅 

see https://github.com/aeternity/ga-multisig-contract/pull/23

but I would be happy to finally see this stuff published in the repos 🙏

**Comment by hanssv** [comment]
Yeah, we've "sold" the report, so I don't feel 100% comfortable putting it here 🤔

**Comment by marc0olo** [comment]
the readme in general needs to be improved @kenodressel @bogdan-manole - there is absolutely no background info about anything instead of running the scripts
